server:
    port: 8082

spring:
    application:
        name: nacos-provider
    cloud:
        nacos:
            discovery:
                server-addr: 127.0.0.1:8848
                #namespace: 6228d265-5167-4ed1-877f-2deb8704f6e3
                metadata:
                    name: provider

feign:
    client.access-token:
        dataMap:
            nacos-consumer: NDQ0NjQxNEI2RjQ2NDg1NjMzNzc2Nzc0MzAzNTYxNjg3MTQzMzEzOTQ1NzM1MDM5MzE1NTZBNEE3MTc2NjE3QTU0NTkzMDM2NzE3MTQ2Mzg0QzRENzM

corpCode: Yibee.com
useLocalCache: false