server:
  port: 8080
spring:
  application:
    name: nacos-geteway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: nacos-provider
          uri: lb://nacos-provider
          predicates:
            - Path=/config/**
        - id: nacos-consumer
          uri: lb://nacos-consumer
          predicates:
            - Path=/test/**